In [3]:
import numpy as np

## 创建Numpy数组

In [2]:
a = np.array([2,3,4,5,6])
a

array([2, 3, 4, 5, 6])

In [6]:
A = np.array(
    [
        [3,4,5],
        [7,8,9]
    ]
)

## numpy数组相关属性

In [5]:
a.ndim #维度

1

In [7]:
A.ndim

2

In [9]:
a.dtype

dtype('int64')

## 创建数组

In [12]:
np.ones(5,dtype="int64")

array([1, 1, 1, 1, 1])

In [14]:
np.ones_like(A, dtype="float64")#形状形同

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros([3,4],dtype="int64")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])