## 索引

In [1]:
import numpy as np

In [2]:
a = np.arange(8)

In [3]:
a[-1]

np.int64(7)

In [5]:
a[3:5]

array([3, 4])

In [6]:
a[4:]

array([4, 5, 6, 7])

In [7]:
a[]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
a[::3]

array([0, 3, 6])

In [9]:
a[::-1]#倒序输出

array([7, 6, 5, 4, 3, 2, 1, 0])

In [19]:
A = np.array([
    [1,2,3,4,5],
    [4,5,6,7,8],
    [5,8,4,7,7]
])

In [20]:
A[-1]

array([5, 8, 4, 7, 7])

In [24]:
A[1:,0]

array([4, 5])

In [25]:
A[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
X = A[:2,:3].copy() #注意深拷贝和浅拷贝

In [28]:
X[0,0] = 100

In [29]:
A[0,0]

np.int64(1)