## 索引

In [1]:
import numpy as np

In [2]:
a = np.arange(8)

In [3]:
a[-1]

np.int64(7)

In [5]:
a[3:5]

array([3, 4])

In [6]:
a[4:]

array([4, 5, 6, 7])

In [7]:
a[]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
a[::3]

array([0, 3, 6])

In [9]:
a[::-1]#倒序输出

array([7, 6, 5, 4, 3, 2, 1, 0])

In [19]:
A = np.array([
    [1,2,3,4,5],
    [4,5,6,7,8],
    [5,8,4,7,7]
])

In [20]:
A[-1]

array([5, 8, 4, 7, 7])

In [24]:
A[1:,0]

array([4, 5])

In [25]:
A[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
X = A[:2,:3].copy() #注意深拷贝和浅拷贝

In [28]:
X[0,0] = 100

In [29]:
A[0,0]

np.int64(1)

In [2]:
import numpy as np
x = np.arange(10)
x[2:8]

array([2, 3, 4, 5, 6, 7])

In [3]:
index = [1,5,9]
x[index]

array([1, 5, 9])

In [4]:
index= np.array([
    [1,2,3],
    [5,6,7]
])
x[index]

array([[1, 2, 3],
       [5, 6, 7]])

In [5]:
X = x.reshape(2,-1)

In [6]:
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
row = np.array([0,1,1])
col = np.array([0,2,4])
X[row,col]

array([0, 7, 9])

In [8]:
 X[row,:2]

array([[0, 1],
       [5, 6],
       [5, 6]])

In [10]:
x[x==5]

array([5])

In [12]:
x[x**2==9]

array([3])

In [13]:
np.sum(x>5)

np.int64(4)

In [14]:
x>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [15]:
np.any(x>5)

np.True_

In [18]:
np.sum(X%2==0,axis=1)

array([3, 2])