In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [5]:
%%time
b = a * 2
b

CPU times: user 51 μs, sys: 1e+03 ns, total: 52 μs
Wall time: 59.8 μs


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
c = np.arange(1,11,0.5)
len(c)

20

In [8]:
C = np.arange(1,11,0.5).reshape(4,5)

In [9]:
C

array([[ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5]])

In [10]:
np.exp(C)

array([[2.71828183e+00, 4.48168907e+00, 7.38905610e+00, 1.21824940e+01,
        2.00855369e+01],
       [3.31154520e+01, 5.45981500e+01, 9.00171313e+01, 1.48413159e+02,
        2.44691932e+02],
       [4.03428793e+02, 6.65141633e+02, 1.09663316e+03, 1.80804241e+03,
        2.98095799e+03],
       [4.91476884e+03, 8.10308393e+03, 1.33597268e+04, 2.20264658e+04,
        3.63155027e+04]])

In [11]:
np.sin(C)

array([[ 0.84147098,  0.99749499,  0.90929743,  0.59847214,  0.14112001],
       [-0.35078323, -0.7568025 , -0.97753012, -0.95892427, -0.70554033],
       [-0.2794155 ,  0.21511999,  0.6569866 ,  0.93799998,  0.98935825],
       [ 0.79848711,  0.41211849, -0.07515112, -0.54402111, -0.87969576]])

In [12]:
np.log10(C)

array([[0.        , 0.17609126, 0.30103   , 0.39794001, 0.47712125],
       [0.54406804, 0.60205999, 0.65321251, 0.69897   , 0.74036269],
       [0.77815125, 0.81291336, 0.84509804, 0.87506126, 0.90308999],
       [0.92941893, 0.95424251, 0.97772361, 1.        , 1.0211893 ]])

In [14]:
C**3 #幂运算

array([[1.000000e+00, 3.375000e+00, 8.000000e+00, 1.562500e+01,
        2.700000e+01],
       [4.287500e+01, 6.400000e+01, 9.112500e+01, 1.250000e+02,
        1.663750e+02],
       [2.160000e+02, 2.746250e+02, 3.430000e+02, 4.218750e+02,
        5.120000e+02],
       [6.141250e+02, 7.290000e+02, 8.573750e+02, 1.000000e+03,
        1.157625e+03]])

In [25]:
Y = np.linspace(10,30,4).reshape(2,2)
X = np.linspace(10,20,4).reshape(2,2)
X,Y

(array([[10.        , 13.33333333],
        [16.66666667, 20.        ]]),
 array([[10.        , 16.66666667],
        [23.33333333, 30.        ]]))

In [26]:
X+Y

array([[20., 30.],
       [40., 50.]])

In [27]:
X*Y #哈达玛乘积

array([[100.        , 222.22222222],
       [388.88888889, 600.        ]])

In [28]:
X.dot(Y)#点积

array([[411.11111111, 566.66666667],
       [633.33333333, 877.77777778]])

In [29]:
X.T

array([[10.        , 16.66666667],
       [13.33333333, 20.        ]])

In [30]:
V = np.linalg.inv(X)# 逆矩阵

In [31]:
X.dot(V)

array([[ 1.00000000e+00, -1.18423789e-16],
       [-1.33226763e-15,  1.00000000e+00]])