In [3]:
import numpy as np

## 创建Numpy数组

In [2]:
a = np.array([2,3,4,5,6])
a

array([2, 3, 4, 5, 6])

In [6]:
A = np.array(
    [
        [3,4,5],
        [7,8,9]
    ]
)

## numpy数组相关属性

In [5]:
a.ndim #维度

1

In [7]:
A.ndim

2

In [9]:
a.dtype

dtype('int64')

## 创建数组

In [12]:
np.ones(5,dtype="int64")

array([1, 1, 1, 1, 1])

In [14]:
np.ones_like(A, dtype="float64")#形状形同

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros([3,4],dtype="int64")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
np.full([3,4],234)

array([[234, 234, 234, 234],
       [234, 234, 234, 234],
       [234, 234, 234, 234]])

In [19]:
np.empty([2,4])#数组每个位置上都是接近于0

array([[0.00000000e+000, 0.00000000e+000, 5.21501920e-310,
        2.46151512e-312],
       [8.71600396e-312, 6.93713539e-310, 2.37663529e-312,
        4.99006302e-322]])

In [20]:
np.arange(10) # 就输出10个数据

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,10,4) #4表示的是间隔

array([1, 5, 9])

In [26]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
np.linspace(0,10,6)#6表示的是个数

array([ 0.,  2.,  4.,  6.,  8., 10.])

## 随机数

In [30]:
np.random.random() #[0, 1)

0.10460253132698094

In [31]:
np.random.random((3,6))

array([[0.36973709, 0.44406925, 0.57069439, 0.38928101, 0.50430667,
        0.31380136],
       [0.28560062, 0.01097286, 0.13682144, 0.07394096, 0.84332396,
        0.59110852],
       [0.72030604, 0.85191565, 0.23120277, 0.67602279, 0.96530583,
        0.18410434]])

In [32]:
np.random.rand(3,4)#这里不需要传入元组

array([[0.24639891, 0.97698311, 0.5716692 , 0.4331549 ],
       [0.49430183, 0.67508223, 0.10879845, 0.82327126],
       [0.25577969, 0.49480999, 0.03427467, 0.95003961]])

In [33]:
np.random.randint(5) #[0, 5)

2

In [38]:
np.random.randint(5,10,size=8) #[5, 10)生成8个随机数

array([7, 6, 5, 6, 6, 8, 9, 7])

In [41]:
np.random.randint(5,10,size=(3,4))

array([[8, 6, 7, 6],
       [5, 9, 8, 6],
       [6, 8, 8, 8]])

## 标准正态分布

In [43]:
np.random.randn(4)#生成来自标准正态分布（均值为0，标准差为1）的随机数(4) 表示生成一个包含 4 个元素的一维数组

array([-1.67659598, -1.46245311, -1.53919177, -1.18812693])

## 高斯分布数据

In [44]:
np.random.normal(10,200,5)#loc = 10：均值（分布的中心位置）
#scale = 200：标准差（分布的离散程度）
#size = 5：输出数组的形状（生成5个随机数）

array([ 593.11430356,   33.67168467, -249.14445942,  422.32674543,
         13.63381893])

## 均匀分布随机数的函数

In [45]:
np.random.uniform(1,5)#low = 1：区间下限（包含）；high = 5：区间上限（不包含）；size：未指定时默认生成 1 个随机数

4.133182327739025