In [9]:
import numpy as np

## 数组的合并

In [10]:
X = np.arange(12).reshape(3,4)

In [11]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
a = np.array([1,1,1,1])

In [13]:
np.vstack((X,a)) #竖直方向合并

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  1,  1,  1]])

In [14]:
C = np.full((3,2),34)
np.hstack((X,C))

array([[ 0,  1,  2,  3, 34, 34],
       [ 4,  5,  6,  7, 34, 34],
       [ 8,  9, 10, 11, 34, 34]])

In [15]:
## 数组的拆分

In [16]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.vsplit(X,[1]) #[0:1] [1:]

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

In [20]:
A1,A2 = np.hsplit(X,[2])#纵向拆分 

In [21]:
A1,A2

(array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]))

In [23]:
np.hsplit(X,[1,3])#[0,1] [1,3][3:]

[array([[0],
        [4],
        [8]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3],
        [ 7],
        [11]])]