## 常见的统计运算

In [1]:
import numpy as np

In [2]:
x = np.arange(5000)

In [3]:
np.max(x)

np.int64(4999)

In [11]:
X = x.reshape(50,-1)
X.shape

(50, 100)

In [12]:
np.min(X,axis=1) #每行最小值

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100,
       2200, 2300, 2400, 2500, 2600, 2700, 2800, 2900, 3000, 3100, 3200,
       3300, 3400, 3500, 3600, 3700, 3800, 3900, 4000, 4100, 4200, 4300,
       4400, 4500, 4600, 4700, 4800, 4900])

In [13]:
np.max(X,axis=0)#每列最大值

array([4900, 4901, 4902, 4903, 4904, 4905, 4906, 4907, 4908, 4909, 4910,
       4911, 4912, 4913, 4914, 4915, 4916, 4917, 4918, 4919, 4920, 4921,
       4922, 4923, 4924, 4925, 4926, 4927, 4928, 4929, 4930, 4931, 4932,
       4933, 4934, 4935, 4936, 4937, 4938, 4939, 4940, 4941, 4942, 4943,
       4944, 4945, 4946, 4947, 4948, 4949, 4950, 4951, 4952, 4953, 4954,
       4955, 4956, 4957, 4958, 4959, 4960, 4961, 4962, 4963, 4964, 4965,
       4966, 4967, 4968, 4969, 4970, 4971, 4972, 4973, 4974, 4975, 4976,
       4977, 4978, 4979, 4980, 4981, 4982, 4983, 4984, 4985, 4986, 4987,
       4988, 4989, 4990, 4991, 4992, 4993, 4994, 4995, 4996, 4997, 4998,
       4999])

In [14]:
np.sum(X,axis=1)

array([  4950,  14950,  24950,  34950,  44950,  54950,  64950,  74950,
        84950,  94950, 104950, 114950, 124950, 134950, 144950, 154950,
       164950, 174950, 184950, 194950, 204950, 214950, 224950, 234950,
       244950, 254950, 264950, 274950, 284950, 294950, 304950, 314950,
       324950, 334950, 344950, 354950, 364950, 374950, 384950, 394950,
       404950, 414950, 424950, 434950, 444950, 454950, 464950, 474950,
       484950, 494950])

In [17]:
np.median(X,axis=0)#取中位数

array([2450., 2451., 2452., 2453., 2454., 2455., 2456., 2457., 2458.,
       2459., 2460., 2461., 2462., 2463., 2464., 2465., 2466., 2467.,
       2468., 2469., 2470., 2471., 2472., 2473., 2474., 2475., 2476.,
       2477., 2478., 2479., 2480., 2481., 2482., 2483., 2484., 2485.,
       2486., 2487., 2488., 2489., 2490., 2491., 2492., 2493., 2494.,
       2495., 2496., 2497., 2498., 2499., 2500., 2501., 2502., 2503.,
       2504., 2505., 2506., 2507., 2508., 2509., 2510., 2511., 2512.,
       2513., 2514., 2515., 2516., 2517., 2518., 2519., 2520., 2521.,
       2522., 2523., 2524., 2525., 2526., 2527., 2528., 2529., 2530.,
       2531., 2532., 2533., 2534., 2535., 2536., 2537., 2538., 2539.,
       2540., 2541., 2542., 2543., 2544., 2545., 2546., 2547., 2548.,
       2549.])

In [18]:
np.std(X) #标准差

np.float64(1443.3756441065507)

In [19]:
np.var(X) #方差

np.float64(2083333.25)

In [21]:
Z = np.random.normal(0,10,4000)
np.mean(Z), np.std(Z)

(np.float64(0.15660213285925398), np.float64(10.167532747061758))

In [22]:
np.ptp(Z) #元素最大值和最小值的差

np.float64(78.74484750161764)

### 百分位数

In [27]:
q = np.linspace(0,100,4)
q,np.percentile(X,q)

(array([  0.        ,  33.33333333,  66.66666667, 100.        ]),
 array([   0.        , 1666.33333333, 3332.66666667, 4999.        ]))