In [1]:
import numpy as np

In [3]:
x = np.random.normal(0,1,size=100000)
x

array([ 1.13141677,  0.08135344, -0.46115634, ..., -0.55209553,
       -0.89713217, -2.17977757])

In [4]:
np.min(x)

np.float64(-4.0908213414655386)

In [7]:
np.argmin(x)

np.int64(89730)

In [8]:
x[np.argmin(x)]

np.float64(-4.0908213414655386)

## 排序

In [11]:
x = np.arange(10)
np.random.shuffle(x)
x

array([0, 2, 5, 4, 6, 8, 9, 1, 3, 7])

In [14]:
x.sort()
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 使用索引

In [16]:
np.random.shuffle(x)
x

array([3, 8, 9, 2, 0, 7, 4, 1, 5, 6])

In [17]:
np.argsort(x)

array([4, 7, 3, 0, 6, 8, 9, 5, 1, 2])

In [18]:
x[4]

np.int64(0)

## partition 分区

In [30]:
y = np.arange(20)

In [32]:
np.random.shuffle(y)
y

array([14,  0,  9, 16, 11,  7, 12, 15,  1, 18,  2,  4,  5, 19,  8, 10,  6,
       13,  3, 17])

In [34]:
np.partition(y,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
np.argpartition(y,10)

array([ 1,  8, 10, 18, 11, 12, 16,  5, 14,  2, 15,  4,  6, 17,  0,  7,  3,
       19,  9, 13])

In [37]:
y[10]

np.int64(2)

## 高维情况

In [38]:
X = np.random.randint(10,size=(5,5,5))
X

array([[[8, 9, 4, 4, 2],
        [4, 3, 5, 0, 2],
        [9, 3, 4, 9, 1],
        [7, 2, 3, 8, 6],
        [8, 6, 8, 0, 7]],

       [[1, 0, 4, 7, 9],
        [0, 2, 3, 6, 9],
        [5, 6, 3, 3, 4],
        [5, 5, 5, 1, 4],
        [3, 7, 3, 3, 1]],

       [[0, 9, 4, 7, 6],
        [7, 6, 2, 0, 3],
        [1, 4, 8, 5, 1],
        [0, 8, 6, 6, 8],
        [1, 1, 2, 6, 9]],

       [[2, 0, 3, 6, 5],
        [8, 4, 2, 5, 6],
        [1, 0, 8, 3, 6],
        [7, 8, 1, 8, 3],
        [9, 6, 2, 4, 5]],

       [[3, 6, 5, 7, 0],
        [6, 9, 7, 3, 9],
        [1, 8, 1, 3, 5],
        [5, 1, 3, 3, 1],
        [8, 3, 8, 9, 6]]])